/**
 * Worker environment augmentation for Phase C2.
 *
 * `worker-configuration.d.ts` is generated by `wrangler types` and declares the
 * base bindings from `wrangler.jsonc` on `__BaseEnv_Env`. Both the global `Env`
 * and `Cloudflare.Env` extend that base, so merging here reaches every handler.
 *
 * Three members are added that `wrangler types` cannot know about.
 *  - `OAUTH_KV`. The KV namespace the OAuth provider uses for its token store.
 *    It IS declared in wrangler.jsonc, so a `wrangler types` regen would also
 *    add it. It is kept here so the typecheck stays correct without regenerating
 *    the large generated file.
 *  - `OAUTH_PROVIDER`. Injected at runtime by `@cloudflare/workers-oauth-provider`.
 *    Never a wrangler binding, so it must be declared by hand.
 *  - `TOKEN_ENCRYPTION_KEY`. A Workers secret set via
 *    `wrangler secret put TOKEN_ENCRYPTION_KEY`. Secrets are never in wrangler.jsonc.
 */

import type { OAuthHelpers } from "@cloudflare/workers-oauth-provider";

declare global {
  interface __BaseEnv_Env {
    /** KV namespace used by the OAuth provider token store. */
    OAUTH_KV: KVNamespace;
    /** Runtime OAuth helper injected by the provider wrapper. */
    OAUTH_PROVIDER: OAuthHelpers;
    /** Secret used to derive the AES-256-GCM key for PAT encryption. */
    TOKEN_ENCRYPTION_KEY: string;
  }
}

export {};
